import { Coach } from './types';

export const COACHES: Coach[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    role: 'doctor',
    specialty: 'Anti-Aging & Longevity',
    rating: 4.9,
    hourlyRate: 150,
    experience: 12,
    patientsCount: 340,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400',
    bio: 'Board-certified physician specializing in peptide therapy and longevity medicine.',
    calendlyLink: 'https://calendly.com/drsarahjohnson',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'coach',
    specialty: 'Muscle Gain & Performance',
    rating: 4.8,
    hourlyRate: 85,
    experience: 8,
    patientsCount: 520,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400',
    bio: 'Elite fitness coach with expertise in peptide protocols for muscle building and performance optimization.',
    calendlyLink: 'https://calendly.com/michaelchen',
  },
  {
    id: '3',
    name: 'Dr. Robert Martinez',
    role: 'doctor',
    specialty: 'Recovery & Joint Health',
    rating: 4.9,
    hourlyRate: 180,
    experience: 15,
    patientsCount: 280,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400',
    bio: 'Sports medicine physician specializing in injury recovery and regenerative therapies.',
    calendlyLink: 'https://calendly.com/drrobertmartinez',
  },
  {
    id: '4',
    name: 'Jennifer Lee',
    role: 'coach',
    specialty: 'Fat Loss & Body Recomposition',
    rating: 4.7,
    hourlyRate: 75,
    experience: 6,
    patientsCount: 410,
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400',
    bio: 'Nutrition and fitness coach specializing in peptide-assisted fat loss and body transformation.',
    calendlyLink: 'https://calendly.com/jenniferlee',
  },
  {
    id: '5',
    name: 'Dr. David Thompson',
    role: 'doctor',
    specialty: 'General Wellness & Optimization',
    rating: 4.8,
    hourlyRate: 140,
    experience: 10,
    patientsCount: 380,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400',
    bio: 'Integrative medicine doctor focused on holistic health optimization and peptide therapy.',
    calendlyLink: 'https://calendly.com/drdavidthompson',
  },
];
