import { Peptide } from './types';

export const PEPTIDES: Peptide[] = [
  {
    id: '1',
    name: 'BPC-157',
    category: 'recovery',
    shortDescription: 'Body Protection Compound for tissue repair and gut health',
    fullDescription: 'BPC-157 is a synthetic peptide derived from a protective protein found in the stomach. It has shown promising results in accelerating healing of various tissues including tendons, ligaments, muscles, and the gastrointestinal tract.',
    benefits: [
      'Accelerates healing of muscles, tendons, and ligaments',
      'Supports gut health and digestion',
      'May reduce inflammation',
      'Protects organs and aids in wound healing',
      'Potential neuroprotective effects',
    ],
    risks: [
      'Limited human clinical trials',
      'Possible injection site reactions',
      'Unknown long-term effects',
      'Not FDA approved',
    ],
    dosageExample: '250-500 mcg per day',
    cycleLength: '4-6 weeks',
    experienceLevel: ['beginner', 'intermediate', 'advanced'],
    goals: ['recovery', 'muscle_gain'],
  },
  {
    id: '2',
    name: 'TB-500',
    category: 'recovery',
    shortDescription: 'Thymosin Beta-4 fragment for enhanced recovery and healing',
    fullDescription: 'TB-500 is a synthetic version of Thymosin Beta-4, a peptide naturally found in high concentrations in blood platelets, wound fluid, and other tissues in the body. It promotes healing and recovery.',
    benefits: [
      'Promotes rapid wound healing',
      'Reduces acute and chronic pain',
      'Increases flexibility',
      'Reduces inflammation in joints',
      'Encourages tissue repair',
    ],
    risks: [
      'Limited human studies',
      'Possible dizziness or fatigue',
      'Injection site reactions',
      'Not FDA approved',
    ],
    dosageExample: '2-2.5 mg twice per week',
    cycleLength: '4-6 weeks',
    experienceLevel: ['intermediate', 'advanced'],
    goals: ['recovery'],
  },
  {
    id: '3',
    name: 'Ipamorelin',
    category: 'growth',
    shortDescription: 'Growth hormone secretagogue for muscle gain and fat loss',
    fullDescription: 'Ipamorelin is a selective growth hormone secretagogue and ghrelin receptor agonist. It stimulates the release of growth hormone from the pituitary gland without affecting cortisol levels.',
    benefits: [
      'Stimulates natural GH production',
      'Promotes lean muscle growth',
      'Aids in fat loss',
      'Improves sleep quality',
      'Strengthens bones',
      'Anti-aging effects',
    ],
    risks: [
      'Potential water retention',
      'Increased hunger',
      'Possible joint pain',
      'Not FDA approved for this use',
    ],
    dosageExample: '200-300 mcg 2-3x daily',
    cycleLength: '8-12 weeks',
    experienceLevel: ['beginner', 'intermediate', 'advanced'],
    goals: ['muscle_gain', 'fat_loss', 'longevity'],
  },
  {
    id: '4',
    name: 'CJC-1295',
    category: 'growth',
    shortDescription: 'Long-acting growth hormone releasing hormone analog',
    fullDescription: 'CJC-1295 is a synthetic modification of growth hormone releasing factor (GRF) that increases growth hormone and IGF-1 secretion with minimal effect on cortisol and prolactin.',
    benefits: [
      'Extended GH release',
      'Increased muscle mass',
      'Improved fat metabolism',
      'Better sleep',
      'Enhanced recovery',
      'Anti-aging benefits',
    ],
    risks: [
      'Potential numbness or tingling',
      'Water retention',
      'Increased hunger',
      'Not FDA approved',
    ],
    dosageExample: '1-2 mg per week (DAC) or 100 mcg 1-3x daily (No DAC)',
    cycleLength: '8-12 weeks',
    experienceLevel: ['intermediate', 'advanced'],
    goals: ['muscle_gain', 'fat_loss', 'longevity'],
  },
  {
    id: '5',
    name: 'GHK-Cu',
    category: 'skin',
    shortDescription: 'Copper peptide for skin rejuvenation and wound healing',
    fullDescription: 'GHK-Cu is a naturally occurring copper complex that has been found in human plasma, saliva, and urine. It has powerful regenerative and protective actions.',
    benefits: [
      'Promotes collagen and elastin production',
      'Improves skin firmness and elasticity',
      'Reduces fine lines and wrinkles',
      'Accelerates wound healing',
      'Anti-inflammatory properties',
      'Antioxidant effects',
    ],
    risks: [
      'Possible skin irritation',
      'Allergic reactions in some individuals',
      'Limited long-term studies',
    ],
    dosageExample: '1-3 mg per day (subcutaneous) or topical application',
    cycleLength: '4-8 weeks',
    experienceLevel: ['beginner', 'intermediate', 'advanced'],
    goals: ['longevity'],
  },
  {
    id: '6',
    name: 'AOD-9604',
    category: 'fat_loss',
    shortDescription: 'Modified fragment of human growth hormone for fat loss',
    fullDescription: 'AOD-9604 is a modified form of amino acids 176-191 of the GH polypeptide. It works by stimulating the breakdown of fat while inhibiting lipogenesis.',
    benefits: [
      'Targets stubborn fat deposits',
      'No effect on blood sugar or growth',
      'Preserves lean muscle mass',
      'May improve cartilage repair',
      'Well-tolerated',
    ],
    risks: [
      'Possible injection site reactions',
      'Limited human trials',
      'Not FDA approved',
    ],
    dosageExample: '250-500 mcg per day',
    cycleLength: '6-8 weeks',
    experienceLevel: ['beginner', 'intermediate', 'advanced'],
    goals: ['fat_loss'],
  },
  {
    id: '7',
    name: 'Semax',
    category: 'cognitive',
    shortDescription: 'Nootropic peptide for cognitive enhancement and neuroprotection',
    fullDescription: 'Semax is a synthetic peptide drug developed in Russia. It is a heptapeptide, synthetic analog of adrenocorticotropic hormone (ACTH). Used for cognitive enhancement and neuroprotection.',
    benefits: [
      'Enhances memory and learning',
      'Increases focus and mental clarity',
      'Neuroprotective properties',
      'May reduce anxiety',
      'Improves mood',
    ],
    risks: [
      'Possible headaches',
      'Irritability in some users',
      'Not FDA approved',
      'Limited Western research',
    ],
    dosageExample: '300-600 mcg per day (nasal spray)',
    cycleLength: '2-4 weeks',
    experienceLevel: ['intermediate', 'advanced'],
    goals: ['longevity'],
  },
  {
    id: '8',
    name: 'Melanotan II',
    category: 'skin',
    shortDescription: 'Synthetic peptide for tanning and potential fat loss',
    fullDescription: 'Melanotan II is a synthetic analog of the peptide hormone α-melanocyte-stimulating hormone (α-MSH). It stimulates melanogenesis and increases sexual arousal.',
    benefits: [
      'Promotes skin tanning',
      'May reduce appetite',
      'Potential fat loss effects',
      'Increased libido',
    ],
    risks: [
      'Nausea (especially initially)',
      'Facial flushing',
      'Increased moles and freckles',
      'Unknown long-term effects',
      'Not FDA approved',
    ],
    dosageExample: '250-500 mcg per day',
    cycleLength: '2-4 weeks loading, then maintenance',
    experienceLevel: ['intermediate', 'advanced'],
    goals: ['fat_loss'],
  },
];
